version: '3.8'

services:
  service:
    command: ['npm', 'run', 'dev']
    environment:
      - NODE_ENV=development
      - DEBUG=apply-flow-service:*
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9229:9229"

  gateway:
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/data/nginx/conf.d:/etc/nginx/conf.d:ro

  mountebank:
    volumes:
      - ./docker/data/mountebank/imposters:/app/imposters:ro
      - ./config:/app/config:ro
      - ./fixtures:/app/fixtures:ro

  vault:
    volumes:
      - ./docker/data/vault:/usr/src/app/vault-data:rw

  redis:
    volumes:
      - ./docker/data/redis:/usr/local/etc/redis:rw
    ports:
      - "6379:6379"