version: '3.9'

services:
  # Tunnel
  gateway:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '4501:80'

  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    command: ['npx', 'chassis-start-watch', '--inspect=0.0.0.0:9229']
    env_file:
      - ./local.env
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
    depends_on:
      - gateway
      - vault
      - redis
      - mountebank
    volumes:
      - ./flows:/usr/src/app/flows
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./.npmrc:/usr/src/app/.npmrc
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - '9227:9229'

  mountebank:
    image: bbyars/mountebank:2.6.0
    command: ['mb', '--configfile', 'imposters/index.ejs', '--allowInjection']
    ports:
      - "2525:2525"
    volumes:
      - ./docker/data/mountebank/imposters:/app/imposters
      - ./config:/app/config
      - ./fixtures:/app/fixtures
  ci:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    command: ['npx', 'chassis-test-watch']
    volumes:
      - ./.coverage:/usr/src/app/.coverage
      - ./flows_test:/usr/src/app/flows
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./.npmrc:/usr/src/app/.npmrc
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    depends_on:
      - vault
      - mountebank
    env_file:
      - ./test.env

  prod:
    image: earnest/apply-flow-service:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    environment:
      - APP_ENV=production
    ports:
      - 3020:3000

  vault:
    environment:
      - VAULT_AUTH_TOKEN=fnord
    image: earnest/vault-dev:latest
    volumes:
      - ./docker/data/vault:/usr/src/app/vault-data

  redis:
    image: redis:6.0.20
    volumes:
      - ./docker/data/redis:/usr/local/etc/redis
    ports:
      - 6379

volumes:
  history:
  database:
  node_modules:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24
