version: '3.9'

services:
  # Tunnel
  gateway:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '4501:80'

  service:
    image: earnest/apply-flow-service:local
    command: ['npx', 'chassis-start-watch', '--inspect=0.0.0.0:9229']
    env_file:
      - ./local.env
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
    depends_on:
      gateway:
        condition: service_healthy
      vault:
        condition: service_healthy
      redis:
        condition: service_healthy
      mountebank:
        condition: service_healthy
    volumes:
      - ./flows:/usr/src/app/flows
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./.npmrc:/usr/src/app/.npmrc
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - '9230:9229'

  mountebank:
    image: bbyars/mountebank:2.6.0
    command: ['mb', '--configfile', 'imposters/index.ejs', '--allowInjection']
    ports:
      - "2525:2525"
    volumes:
      - ./docker/data/mountebank/imposters:/app/imposters
      - ./config:/app/config
      - ./fixtures:/app/fixtures

  vault:
    environment:
      - VAULT_AUTH_TOKEN=fnord
    image: earnest/vault-dev:latest
    volumes:
      - ./docker/data/vault:/usr/src/app/vault-data

  redis:
    image: redis:6.0.20
    volumes:
      - ./docker/data/redis:/usr/local/etc/redis
    ports:
      - 6379:6379

volumes:
  history:
  database:


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24
