services:
  gateway:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '4501:80'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/"]

  service:
    image: earnest/apply-flow-service:local
    command: ['npx', 'chassis-start-watch', '--inspect=0.0.0.0:9229']
    env_file:
      - ./local.env
    depends_on:
      vault:
        condition: service_healthy
      redis:
        condition: service_healthy
      mountebank:
        condition: service_healthy
    volumes:
      - ./flows:/usr/src/app/flows
      - ./src:/usr/src/app/src
      - ./.npmrc:/usr/src/app/.npmrc
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - '9230:9229'

  mountebank:
    image: bbyars/mountebank:2.6.0
    command: ['mb', '--configfile', 'imposters/index.ejs', '--allowInjection']
    ports:
      - "2525:2525"
    volumes:
      - ./docker/data/mountebank/imposters:/app/imposters
      - ./config:/app/config
      - ./fixtures:/app/fixtures
    healthcheck:
      test: ['CMD', 'wget', '-nv', '-t1', '--spider', 'http://localhost:2525/']
      interval: 4s
      timeout: 30s
      start_period: 3s

  vault:
    environment:
      - VAULT_AUTH_TOKEN=fnord
    image: earnest/vault-dev:latest
    volumes:
      - ./docker/data/vault:/usr/src/app/vault-data
    healthcheck:
      test: curl --fail http://localhost:9000/v1/sys/health || exit 1
      interval: 10s
      retries: 5
      start_period: 40s
      timeout: 10s

  redis:
    image: redis:6.0.20
    volumes:
      - ./docker/data/redis:/usr/local/etc/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - 6379:6379

volumes:
  history:
  database:


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24
